import { MigrationInterface, QueryRunner } from "typeorm";

export class GeneratedMigration1749312706361 implements MigrationInterface {
    name = 'GeneratedMigration1749312706361'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`brands\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`logo_media_id\` int NULL, \`description\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b15428f362be2200922952dc26\` (\`slug\`), UNIQUE INDEX \`IDX_96db6bbbaa6f23cad26871339b\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attributes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_89afb34fd1fdb2ceb1cea6c57d\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attribute_values\` (\`id\` int NOT NULL AUTO_INCREMENT, \`attributeId\` int NOT NULL, \`value\` varchar(100) NOT NULL, \`colorCode\` varchar(7) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_39d8e6de4e79a6ba892428f16f\` (\`attributeId\`, \`value\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_variant_attribute_value\` (\`productVariantId\` int NOT NULL, \`attributeValueId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`productVariantId\`, \`attributeValueId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cart_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NULL, \`sessionId\` varchar(255) NULL, \`productVariantId\` int NOT NULL, \`quantity\` int NOT NULL, \`addedAt\` timestamp NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_f314e80e7fb1127d86b78d0f1a\` (\`sessionId\`, \`productVariantId\`), UNIQUE INDEX \`IDX_029e3499726b1681378523174d\` (\`userId\`, \`productVariantId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`wishlist_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`productVariantId\` int NOT NULL, \`addedAt\` timestamp NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_a548c14f73c499f50d90a07924\` (\`userId\`, \`productVariantId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`orderId\` int NOT NULL, \`productVariantId\` int NOT NULL, \`productNameSnapshot\` varchar(255) NOT NULL, \`variantSkuSnapshot\` varchar(100) NOT NULL, \`unitPriceAtPurchase\` decimal(12,2) NOT NULL, \`quantity\` int NOT NULL, \`lineItemTotalAmount\` decimal(15,2) NOT NULL, \`lineItemDiscountAmount\` decimal(12,2) NOT NULL DEFAULT '0.00', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`flash_sales\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`startsAt\` datetime NOT NULL, \`endsAt\` datetime NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`banner_media_id\` int NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`flash_sale_products\` (\`id\` int NOT NULL AUTO_INCREMENT, \`flashSaleId\` int NOT NULL, \`productVariantId\` int NOT NULL, \`flashSalePrice\` decimal(12,2) NOT NULL, \`quantityLimit\` int NOT NULL, \`quantitySold\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_0c600b4f7bde9e298475e32dbf\` (\`flashSaleId\`, \`productVariantId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_variants\` (\`id\` int NOT NULL AUTO_INCREMENT, \`productId\` int NOT NULL, \`variantSku\` varchar(100) NOT NULL, \`costPrice\` decimal(12,2) NULL, \`sellingPrice\` decimal(12,2) NOT NULL, \`stockQuantity\` int NOT NULL DEFAULT '0', \`variant_image_media_id\` int NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_43e4bd183fd6a154d18610efaa\` (\`variantSku\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_gallery_media\` (\`id\` int NOT NULL AUTO_INCREMENT, \`product_id\` int NOT NULL, \`media_id\` int NOT NULL, \`sort_order\` int NULL, \`display_order\` int NOT NULL DEFAULT '0', \`alt_text\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_reviews\` (\`id\` int NOT NULL AUTO_INCREMENT, \`productId\` int NOT NULL, \`userId\` int NOT NULL, \`orderId\` int NULL, \`rating\` tinyint NOT NULL, \`comment\` text NULL, \`status\` enum ('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending', \`reviewedAt\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`baseSku\` varchar(100) NOT NULL, \`shortDescription\` text NULL, \`longDescription\` text NULL, \`categoryId\` int NOT NULL, \`brandId\` int NULL, \`main_cover_image_media_id\` int NULL, \`averageRating\` decimal(3,2) NOT NULL DEFAULT '0.00', \`reviewCount\` int NOT NULL DEFAULT '0', \`status\` enum ('draft', 'published', 'unpublished') NOT NULL DEFAULT 'draft', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_65bcb8d9ba02783f568726efa2\` (\`baseSku\`), UNIQUE INDEX \`IDX_464f927ae360106b783ed0b410\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`parentCategoryId\` int NULL, \`cover_image_media_id\` int NULL, \`description\` text NULL, \`displayOrder\` int NOT NULL DEFAULT '0', \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_f314a8b42f88d87b2dcb7fc491\` (\`slug\`), UNIQUE INDEX \`IDX_a75bfadcd8291a0538ab7abfdc\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_payments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`orderId\` int NOT NULL, \`paymentMethodId\` int NOT NULL, \`externalTransactionId\` varchar(255) NULL, \`amountPaid\` decimal(15,2) NOT NULL, \`paymentTimestamp\` datetime NOT NULL, \`status\` varchar(50) NOT NULL, \`gatewayResponseDetails\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_methods\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`code\` varchar(255) NOT NULL, \`logo_media_id\` int NULL, \`description\` text NULL, \`apiConfiguration\` json NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_f8aad3eab194dfdae604ca1112\` (\`code\`), UNIQUE INDEX \`IDX_a793d7354d7c3aaf76347ee5a6\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`blog_categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`description\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_903a6ea496e83ba9bec10af583\` (\`slug\`), UNIQUE INDEX \`IDX_adc3bc773ccf2fb6f073193fcf\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tags\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`slug\` varchar(100) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b3aa10c29ea4e61a830362bd25\` (\`slug\`), UNIQUE INDEX \`IDX_d90243459a697eadb8ad56e909\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`blog_post_tags\` (\`id\` int NOT NULL AUTO_INCREMENT, \`blogPostId\` int NOT NULL, \`tagId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_ff2e37f996ee6628b5dd539047\` (\`blogPostId\`, \`tagId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`blog_posts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`contentHtml\` text NOT NULL, \`excerpt\` text NULL, \`blogCategoryId\` int NOT NULL, \`authorUserId\` int NULL, \`featured_image_media_id\` int NULL, \`status\` enum ('draft', 'published', 'archived') NOT NULL DEFAULT 'draft', \`publishedAt\` datetime NULL, \`viewCount\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_5b2818a2c45c3edb9991b1c7a5\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`banners\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NULL, \`mediaId\` int NULL, \`linkUrl\` varchar(255) NULL, \`logo_media_id\` int NULL, \`positionKey\` varchar(100) NULL, \`bannerType\` varchar(100) NULL, \`displayOrder\` int NOT NULL DEFAULT '0', \`startsAt\` datetime NULL, \`endsAt\` datetime NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`media\` (\`id\` int NOT NULL AUTO_INCREMENT, \`original_file_name\` varchar(255) NOT NULL, \`stored_file_name\` varchar(255) NOT NULL, \`relative_path\` varchar(255) NOT NULL, \`mime_type\` varchar(100) NULL, \`file_size_bytes\` bigint NULL, \`default_alt_text\` varchar(255) NULL, \`file_type\` enum ('image', 'video', 'document', 'other') NOT NULL DEFAULT 'other', \`purpose\` enum ('user_profile_picture', 'product_main_image', 'product_gallery_image', 'blog_featured_image', 'category_cover_image', 'brand_logo', 'shipping_provider_logo', 'payment_method_logo', 'flash_sale_banner', 'banner_general', 'other') NOT NULL DEFAULT 'other', \`related_entity_id\` bigint NULL, \`thumbnail_path\` varchar(255) NULL, \`medium_path\` varchar(255) NULL, \`uploaded_by_user_id\` int NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE INDEX \`IDX_1468e3819d8bcdc6e518b4054d\` (\`stored_file_name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`shipping_providers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`logo_media_id\` int NULL, \`apiKey\` varchar(255) NULL, \`webhookUrl\` varchar(255) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_5cdac8409dd11e86c1bf5b58b1\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_status_history\` (\`id\` int NOT NULL AUTO_INCREMENT, \`orderId\` int NOT NULL, \`previousStatusCode\` enum ('pending_confirmation', 'processing', 'shipped', 'delivered', 'cancelled', 'returned') NULL, \`newStatusCode\` enum ('pending_confirmation', 'processing', 'shipped', 'delivered', 'cancelled', 'returned') NOT NULL, \`notes\` text NULL, \`changedAt\` datetime NOT NULL, \`changedByUserId\` int NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`promotion_applicability_rules\` (\`id\` int NOT NULL AUTO_INCREMENT, \`promotionId\` int NOT NULL, \`ruleType\` enum ('product', 'category', 'user', 'product_variant') NOT NULL, \`entityId\` bigint NOT NULL, \`applicabilityType\` enum ('include', 'exclude') NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`promotions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(50) NOT NULL, \`description\` text NULL, \`discountType\` enum ('percentage', 'fixed_amount_order', 'free_shipping') NOT NULL, \`discountValue\` decimal(10,2) NOT NULL, \`minimumOrderValue\` decimal(15,2) NULL, \`maximumUsageLimit\` int NULL, \`currentUsageCount\` int NOT NULL DEFAULT '0', \`usageLimitPerUser\` int NULL, \`startsAt\` datetime NOT NULL, \`endsAt\` datetime NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_8ab10e580f70c3d2e2e4b31ebf\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_promotion\` (\`orderId\` int NOT NULL, \`promotionId\` int NOT NULL, \`amountDiscounted\` decimal(15,2) NOT NULL, \`appliedAt\` timestamp NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`orderId\`, \`promotionId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` int NOT NULL AUTO_INCREMENT, \`orderCode\` varchar(50) NOT NULL, \`userId\` int NULL, \`customerEmail\` varchar(255) NOT NULL, \`customerFullName\` varchar(255) NOT NULL, \`customerPhoneNumber\` varchar(20) NOT NULL, \`shippingAddressId\` int NULL, \`shippingAddressSnapshotText\` text NOT NULL, \`subtotalAmount\` decimal(15,2) NOT NULL, \`discountAmount\` decimal(15,2) NOT NULL DEFAULT '0.00', \`shippingFeeAmount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`grandTotalAmount\` decimal(15,2) NOT NULL, \`paymentMethodId\` int NOT NULL, \`paymentStatus\` enum ('pending', 'paid', 'failed', 'refunded') NOT NULL DEFAULT 'pending', \`orderStatusCode\` enum ('pending_confirmation', 'processing', 'shipped', 'delivered', 'cancelled', 'returned') NOT NULL DEFAULT 'pending_confirmation', \`customerNotes\` text NULL, \`internalNotes\` text NULL, \`shippingProviderId\` int NULL, \`trackingNumber\` varchar(100) NULL, \`estimatedDeliveryDate\` date NULL, \`placedAt\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_a97c808a83af1497276bf85e5b\` (\`orderCode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`addresses\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`recipientFullName\` varchar(255) NOT NULL, \`recipientPhoneNumber\` varchar(20) NOT NULL, \`streetAddress\` varchar(255) NOT NULL, \`ward\` varchar(255) NOT NULL, \`district\` varchar(255) NOT NULL, \`cityProvince\` varchar(255) NOT NULL, \`country\` varchar(100) NOT NULL DEFAULT 'Vietnam', \`addressType\` enum ('HOME', 'OFFICE', 'OTHER') NULL, \`isDefault\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`password_reset_codes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`code\` varchar(255) NOT NULL, \`expiresAt\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_f1399d5463bc09f8075a5739da\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`email_verification_codes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(255) NOT NULL, \`expiresAt\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`userId\` int NOT NULL, UNIQUE INDEX \`IDX_97bef998b0d463cb053643822a\` (\`userId\`), UNIQUE INDEX \`IDX_4d6d04ed4d25fab71f214490af\` (\`code\`), UNIQUE INDEX \`REL_97bef998b0d463cb053643822a\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permissions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`resource\` enum ('users', 'products', 'media', 'cms', 'blogs', 'banners', 'statistics', 'orders', 'payments', 'promotions', 'carts', 'addresses', 'roles') NOT NULL, \`action\` text NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(50) NOT NULL, \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_permissions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`action\` text NOT NULL, \`roleId\` int NULL, \`permissionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NULL, \`fullName\` varchar(255) NULL, \`phoneNumber\` varchar(20) NULL, \`googleId\` varchar(255) NULL, \`accountType\` enum ('local', 'google') NOT NULL DEFAULT 'local', \`role_id\` int NOT NULL, \`refreshToken\` varchar(500) NULL, \`emailVerifiedAt\` datetime NULL, \`status\` enum ('active', 'inactive', 'banned') NOT NULL DEFAULT 'inactive', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`profile_picture_media_id\` int NULL, UNIQUE INDEX \`IDX_f382af58ab36057334fb262efd\` (\`googleId\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cms_pages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`contentHtml\` text NOT NULL, \`status\` enum ('draft', 'published', 'unpublished') NOT NULL DEFAULT 'published', \`metaTitle\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_164bf011d905e86e677bc86a1e\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD CONSTRAINT \`FK_0c9db908e3f012e6cc396d80782\` FOREIGN KEY (\`logo_media_id\`) REFERENCES \`media\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` ADD CONSTRAINT \`FK_b8f8e1d9141248b538c9285574e\` FOREIGN KEY (\`attributeId\`) REFERENCES \`attributes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variant_attribute_value\` ADD CONSTRAINT \`FK_a84e0dae505692683b927785a1d\` FOREIGN KEY (\`productVariantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variant_attribute_value\` ADD CONSTRAINT \`FK_4beb4cb408f95903f73fc86da5e\` FOREIGN KEY (\`attributeValueId\`) REFERENCES \`attribute_values\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_84e765378a5f03ad9900df3a9ba\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_98ba4bbf6e3611d2062b898f5c1\` FOREIGN KEY (\`productVariantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlist_items\` ADD CONSTRAINT \`FK_3167e7490f12ed329a36703d980\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlist_items\` ADD CONSTRAINT \`FK_caec81ce42bda56a3f034ed5bc8\` FOREIGN KEY (\`productVariantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_f1d359a55923bb45b057fbdab0d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_9cf6578d9f8c7f43cc96c7af6d8\` FOREIGN KEY (\`productVariantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`flash_sales\` ADD CONSTRAINT \`FK_148d909ad62aa34af66c4a610c7\` FOREIGN KEY (\`banner_media_id\`) REFERENCES \`media\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`flash_sale_products\` ADD CONSTRAINT \`FK_471647667659867ab1d7420b67d\` FOREIGN KEY (\`flashSaleId\`) REFERENCES \`flash_sales\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`flash_sale_products\` ADD CONSTRAINT \`FK_3233b6124167cf725d6c5f2f5db\` FOREIGN KEY (\`productVariantId\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_f515690c571a03400a9876600b5\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_f797438e3f4a0e149f45efdf1e5\` FOREIGN KEY (\`variant_image_media_id\`) REFERENCES \`media\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_gallery_media\` ADD CONSTRAINT \`FK_4b3d1b58e52a6d561fd1af42f45\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_gallery_media\` ADD CONSTRAINT \`FK_f832be7e52742b48d992a7c3bb6\` FOREIGN KEY (\`media_id\`) REFERENCES \`media\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` ADD CONSTRAINT \`FK_32edd80d91dff1bc19e79c8f16d\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` ADD CONSTRAINT \`FK_964f13abf796aca25d7e5849c64\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` ADD CONSTRAINT \`FK_f1432cc7dde8c52ac11151d439e\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_ff56834e735fa78a15d0cf21926\` FOREIGN KEY (\`categoryId\`) REFERENCES \`product_categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_ea86d0c514c4ecbb5694cbf57df\` FOREIGN KEY (\`brandId\`) REFERENCES \`brands\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_ad119f69ee3f38c080449fab7d9\` FOREIGN KEY (\`main_cover_image_media_id\`) REFERENCES \`media\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_categories\` ADD CONSTRAINT \`FK_2af33ac5f819c1535106938e3a5\` FOREIGN KEY (\`parentCategoryId\`) REFERENCES \`product_categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_categories\` ADD CONSTRAINT \`FK_c100f6462120f37e1b51d60271d\` FOREIGN KEY (\`cover_image_media_id\`) REFERENCES \`media\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_payments\` ADD CONSTRAINT \`FK_abca480893311e20150f01b2f15\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_payments\` ADD CONSTRAINT \`FK_e026d8707799599bb6fa5729439\` FOREIGN KEY (\`paymentMethodId\`) REFERENCES \`payment_methods\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD CONSTRAINT \`FK_a690f6d39ab8a67283f29b0713a\` FOREIGN KEY (\`logo_media_id\`) REFERENCES \`media\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blog_post_tags\` ADD CONSTRAINT \`FK_927cd428aba5ef67b5e453d986f\` FOREIGN KEY (\`blogPostId\`) REFERENCES \`blog_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blog_post_tags\` ADD CONSTRAINT \`FK_d6e4bd52e7bf4bd69be040cb17d\` FOREIGN KEY (\`tagId\`) REFERENCES \`tags\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD CONSTRAINT \`FK_43c253d266a81448f5f82279d72\` FOREIGN KEY (\`blogCategoryId\`) REFERENCES \`blog_categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD CONSTRAINT \`FK_a22b8be8708cd3ea4d63dd189ca\` FOREIGN KEY (\`authorUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` ADD CONSTRAINT \`FK_bd87dd740ed0df5e7ed8b59b0ce\` FOREIGN KEY (\`featured_image_media_id\`) REFERENCES \`media\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`banners\` ADD CONSTRAINT \`FK_079e741eacc151f629e97cdfd00\` FOREIGN KEY (\`mediaId\`) REFERENCES \`media\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`banners\` ADD CONSTRAINT \`FK_77faceb19819f18cb8431a248ef\` FOREIGN KEY (\`logo_media_id\`) REFERENCES \`media\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`media\` ADD CONSTRAINT \`FK_68c04b3ee10356224d24f61cdd5\` FOREIGN KEY (\`uploaded_by_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_providers\` ADD CONSTRAINT \`FK_eab9637ebbd335215ca3abbf14a\` FOREIGN KEY (\`logo_media_id\`) REFERENCES \`media\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_history\` ADD CONSTRAINT \`FK_689db3835e5550e68d26ca32676\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_status_history\` ADD CONSTRAINT \`FK_a58d197ebde84d00cdf27ae1844\` FOREIGN KEY (\`changedByUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`promotion_applicability_rules\` ADD CONSTRAINT \`FK_905e67e795a6018c2abe356ab06\` FOREIGN KEY (\`promotionId\`) REFERENCES \`promotions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_promotion\` ADD CONSTRAINT \`FK_25226c44bc1062aa9c212a8361d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_promotion\` ADD CONSTRAINT \`FK_df6e4558b74fc62e59239643822\` FOREIGN KEY (\`promotionId\`) REFERENCES \`promotions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_cc4e4adab232e8c05026b2f345d\` FOREIGN KEY (\`shippingAddressId\`) REFERENCES \`addresses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_c137e0afcc291b9135d3e0c3d4e\` FOREIGN KEY (\`paymentMethodId\`) REFERENCES \`payment_methods\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_3637e55fbe686dcf920623a3e67\` FOREIGN KEY (\`shippingProviderId\`) REFERENCES \`shipping_providers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_95c93a584de49f0b0e13f753630\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`password_reset_codes\` ADD CONSTRAINT \`FK_9c30b1d4c6199fd152c128dbd37\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_verification_codes\` ADD CONSTRAINT \`FK_97bef998b0d463cb053643822a3\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_b4599f8b8f548d35850afa2d12c\` FOREIGN KEY (\`roleId\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_06792d0c62ce6b0203c03643cdd\` FOREIGN KEY (\`permissionId\`) REFERENCES \`permissions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_a2cecd1a3531c0b041e29ba46e1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_c91c5ee77f3370d06659ec81319\` FOREIGN KEY (\`profile_picture_media_id\`) REFERENCES \`media\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_c91c5ee77f3370d06659ec81319\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_a2cecd1a3531c0b041e29ba46e1\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_06792d0c62ce6b0203c03643cdd\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_b4599f8b8f548d35850afa2d12c\``);
        await queryRunner.query(`ALTER TABLE \`email_verification_codes\` DROP FOREIGN KEY \`FK_97bef998b0d463cb053643822a3\``);
        await queryRunner.query(`ALTER TABLE \`password_reset_codes\` DROP FOREIGN KEY \`FK_9c30b1d4c6199fd152c128dbd37\``);
        await queryRunner.query(`ALTER TABLE \`addresses\` DROP FOREIGN KEY \`FK_95c93a584de49f0b0e13f753630\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_3637e55fbe686dcf920623a3e67\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_c137e0afcc291b9135d3e0c3d4e\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_cc4e4adab232e8c05026b2f345d\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`order_promotion\` DROP FOREIGN KEY \`FK_df6e4558b74fc62e59239643822\``);
        await queryRunner.query(`ALTER TABLE \`order_promotion\` DROP FOREIGN KEY \`FK_25226c44bc1062aa9c212a8361d\``);
        await queryRunner.query(`ALTER TABLE \`promotion_applicability_rules\` DROP FOREIGN KEY \`FK_905e67e795a6018c2abe356ab06\``);
        await queryRunner.query(`ALTER TABLE \`order_status_history\` DROP FOREIGN KEY \`FK_a58d197ebde84d00cdf27ae1844\``);
        await queryRunner.query(`ALTER TABLE \`order_status_history\` DROP FOREIGN KEY \`FK_689db3835e5550e68d26ca32676\``);
        await queryRunner.query(`ALTER TABLE \`shipping_providers\` DROP FOREIGN KEY \`FK_eab9637ebbd335215ca3abbf14a\``);
        await queryRunner.query(`ALTER TABLE \`media\` DROP FOREIGN KEY \`FK_68c04b3ee10356224d24f61cdd5\``);
        await queryRunner.query(`ALTER TABLE \`banners\` DROP FOREIGN KEY \`FK_77faceb19819f18cb8431a248ef\``);
        await queryRunner.query(`ALTER TABLE \`banners\` DROP FOREIGN KEY \`FK_079e741eacc151f629e97cdfd00\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP FOREIGN KEY \`FK_bd87dd740ed0df5e7ed8b59b0ce\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP FOREIGN KEY \`FK_a22b8be8708cd3ea4d63dd189ca\``);
        await queryRunner.query(`ALTER TABLE \`blog_posts\` DROP FOREIGN KEY \`FK_43c253d266a81448f5f82279d72\``);
        await queryRunner.query(`ALTER TABLE \`blog_post_tags\` DROP FOREIGN KEY \`FK_d6e4bd52e7bf4bd69be040cb17d\``);
        await queryRunner.query(`ALTER TABLE \`blog_post_tags\` DROP FOREIGN KEY \`FK_927cd428aba5ef67b5e453d986f\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP FOREIGN KEY \`FK_a690f6d39ab8a67283f29b0713a\``);
        await queryRunner.query(`ALTER TABLE \`order_payments\` DROP FOREIGN KEY \`FK_e026d8707799599bb6fa5729439\``);
        await queryRunner.query(`ALTER TABLE \`order_payments\` DROP FOREIGN KEY \`FK_abca480893311e20150f01b2f15\``);
        await queryRunner.query(`ALTER TABLE \`product_categories\` DROP FOREIGN KEY \`FK_c100f6462120f37e1b51d60271d\``);
        await queryRunner.query(`ALTER TABLE \`product_categories\` DROP FOREIGN KEY \`FK_2af33ac5f819c1535106938e3a5\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_ad119f69ee3f38c080449fab7d9\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_ea86d0c514c4ecbb5694cbf57df\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_ff56834e735fa78a15d0cf21926\``);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` DROP FOREIGN KEY \`FK_f1432cc7dde8c52ac11151d439e\``);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` DROP FOREIGN KEY \`FK_964f13abf796aca25d7e5849c64\``);
        await queryRunner.query(`ALTER TABLE \`product_reviews\` DROP FOREIGN KEY \`FK_32edd80d91dff1bc19e79c8f16d\``);
        await queryRunner.query(`ALTER TABLE \`product_gallery_media\` DROP FOREIGN KEY \`FK_f832be7e52742b48d992a7c3bb6\``);
        await queryRunner.query(`ALTER TABLE \`product_gallery_media\` DROP FOREIGN KEY \`FK_4b3d1b58e52a6d561fd1af42f45\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_f797438e3f4a0e149f45efdf1e5\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_f515690c571a03400a9876600b5\``);
        await queryRunner.query(`ALTER TABLE \`flash_sale_products\` DROP FOREIGN KEY \`FK_3233b6124167cf725d6c5f2f5db\``);
        await queryRunner.query(`ALTER TABLE \`flash_sale_products\` DROP FOREIGN KEY \`FK_471647667659867ab1d7420b67d\``);
        await queryRunner.query(`ALTER TABLE \`flash_sales\` DROP FOREIGN KEY \`FK_148d909ad62aa34af66c4a610c7\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_9cf6578d9f8c7f43cc96c7af6d8\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_f1d359a55923bb45b057fbdab0d\``);
        await queryRunner.query(`ALTER TABLE \`wishlist_items\` DROP FOREIGN KEY \`FK_caec81ce42bda56a3f034ed5bc8\``);
        await queryRunner.query(`ALTER TABLE \`wishlist_items\` DROP FOREIGN KEY \`FK_3167e7490f12ed329a36703d980\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_98ba4bbf6e3611d2062b898f5c1\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_84e765378a5f03ad9900df3a9ba\``);
        await queryRunner.query(`ALTER TABLE \`product_variant_attribute_value\` DROP FOREIGN KEY \`FK_4beb4cb408f95903f73fc86da5e\``);
        await queryRunner.query(`ALTER TABLE \`product_variant_attribute_value\` DROP FOREIGN KEY \`FK_a84e0dae505692683b927785a1d\``);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` DROP FOREIGN KEY \`FK_b8f8e1d9141248b538c9285574e\``);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP FOREIGN KEY \`FK_0c9db908e3f012e6cc396d80782\``);
        await queryRunner.query(`DROP INDEX \`IDX_164bf011d905e86e677bc86a1e\` ON \`cms_pages\``);
        await queryRunner.query(`DROP TABLE \`cms_pages\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_f382af58ab36057334fb262efd\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` ON \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP TABLE \`permissions\``);
        await queryRunner.query(`DROP INDEX \`REL_97bef998b0d463cb053643822a\` ON \`email_verification_codes\``);
        await queryRunner.query(`DROP INDEX \`IDX_4d6d04ed4d25fab71f214490af\` ON \`email_verification_codes\``);
        await queryRunner.query(`DROP INDEX \`IDX_97bef998b0d463cb053643822a\` ON \`email_verification_codes\``);
        await queryRunner.query(`DROP TABLE \`email_verification_codes\``);
        await queryRunner.query(`DROP INDEX \`IDX_f1399d5463bc09f8075a5739da\` ON \`password_reset_codes\``);
        await queryRunner.query(`DROP TABLE \`password_reset_codes\``);
        await queryRunner.query(`DROP TABLE \`addresses\``);
        await queryRunner.query(`DROP INDEX \`IDX_a97c808a83af1497276bf85e5b\` ON \`orders\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP TABLE \`order_promotion\``);
        await queryRunner.query(`DROP INDEX \`IDX_8ab10e580f70c3d2e2e4b31ebf\` ON \`promotions\``);
        await queryRunner.query(`DROP TABLE \`promotions\``);
        await queryRunner.query(`DROP TABLE \`promotion_applicability_rules\``);
        await queryRunner.query(`DROP TABLE \`order_status_history\``);
        await queryRunner.query(`DROP INDEX \`IDX_5cdac8409dd11e86c1bf5b58b1\` ON \`shipping_providers\``);
        await queryRunner.query(`DROP TABLE \`shipping_providers\``);
        await queryRunner.query(`DROP INDEX \`IDX_1468e3819d8bcdc6e518b4054d\` ON \`media\``);
        await queryRunner.query(`DROP TABLE \`media\``);
        await queryRunner.query(`DROP TABLE \`banners\``);
        await queryRunner.query(`DROP INDEX \`IDX_5b2818a2c45c3edb9991b1c7a5\` ON \`blog_posts\``);
        await queryRunner.query(`DROP TABLE \`blog_posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_ff2e37f996ee6628b5dd539047\` ON \`blog_post_tags\``);
        await queryRunner.query(`DROP TABLE \`blog_post_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_d90243459a697eadb8ad56e909\` ON \`tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_b3aa10c29ea4e61a830362bd25\` ON \`tags\``);
        await queryRunner.query(`DROP TABLE \`tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_adc3bc773ccf2fb6f073193fcf\` ON \`blog_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_903a6ea496e83ba9bec10af583\` ON \`blog_categories\``);
        await queryRunner.query(`DROP TABLE \`blog_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_a793d7354d7c3aaf76347ee5a6\` ON \`payment_methods\``);
        await queryRunner.query(`DROP INDEX \`IDX_f8aad3eab194dfdae604ca1112\` ON \`payment_methods\``);
        await queryRunner.query(`DROP TABLE \`payment_methods\``);
        await queryRunner.query(`DROP TABLE \`order_payments\``);
        await queryRunner.query(`DROP INDEX \`IDX_a75bfadcd8291a0538ab7abfdc\` ON \`product_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_f314a8b42f88d87b2dcb7fc491\` ON \`product_categories\``);
        await queryRunner.query(`DROP TABLE \`product_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_464f927ae360106b783ed0b410\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_65bcb8d9ba02783f568726efa2\` ON \`products\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP TABLE \`product_reviews\``);
        await queryRunner.query(`DROP TABLE \`product_gallery_media\``);
        await queryRunner.query(`DROP INDEX \`IDX_43e4bd183fd6a154d18610efaa\` ON \`product_variants\``);
        await queryRunner.query(`DROP TABLE \`product_variants\``);
        await queryRunner.query(`DROP INDEX \`IDX_0c600b4f7bde9e298475e32dbf\` ON \`flash_sale_products\``);
        await queryRunner.query(`DROP TABLE \`flash_sale_products\``);
        await queryRunner.query(`DROP TABLE \`flash_sales\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_a548c14f73c499f50d90a07924\` ON \`wishlist_items\``);
        await queryRunner.query(`DROP TABLE \`wishlist_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_029e3499726b1681378523174d\` ON \`cart_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_f314e80e7fb1127d86b78d0f1a\` ON \`cart_items\``);
        await queryRunner.query(`DROP TABLE \`cart_items\``);
        await queryRunner.query(`DROP TABLE \`product_variant_attribute_value\``);
        await queryRunner.query(`DROP INDEX \`IDX_39d8e6de4e79a6ba892428f16f\` ON \`attribute_values\``);
        await queryRunner.query(`DROP TABLE \`attribute_values\``);
        await queryRunner.query(`DROP INDEX \`IDX_89afb34fd1fdb2ceb1cea6c57d\` ON \`attributes\``);
        await queryRunner.query(`DROP TABLE \`attributes\``);
        await queryRunner.query(`DROP INDEX \`IDX_96db6bbbaa6f23cad26871339b\` ON \`brands\``);
        await queryRunner.query(`DROP INDEX \`IDX_b15428f362be2200922952dc26\` ON \`brands\``);
        await queryRunner.query(`DROP TABLE \`brands\``);
    }

}
